// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoStock.Data;

public partial class Account
{
    public int AccountId { get; set; }

    /// <summary>
    /// [13] 증권사 이름
    /// </summary>
    public int StockFirmCode { get; set; }

    /// <summary>
    /// [14] 계좌 종류
    /// </summary>
    public int AccountTypeCode { get; set; }

    /// <summary>
    /// 계좌번호
    /// </summary>
    public string AccountNumber { get; set; }

    /// <summary>
    /// 사용가능여부
    /// </summary>
    public bool Enabled { get; set; }

    /// <summary>
    /// 현재 계좌 평가금액
    /// </summary>
    public int CurrentAmount { get; set; }

    /// <summary>
    /// 특이사항
    /// </summary>
    public int CurrentCurrency { get; set; }

    /// <summary>
    /// 현재 현금보유
    /// </summary>
    public string Memo { get; set; }

    public virtual ICollection<AccountDetailHistory> AccountDetailHistories { get; set; } = new List<AccountDetailHistory>();

    public virtual ICollection<AccountDetail> AccountDetails { get; set; } = new List<AccountDetail>();
}