// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoStock.Data;

public partial class Code
{
    public int CodeId { get; set; }

    public int CodeCategoryId { get; set; }

    public string Text { get; set; }

    public bool Enabled { get; set; }

    public string Memo { get; set; }

    public virtual CodeCategory CodeCategory { get; set; }
}