//<auto-generated> This file has been generated by Gccg. </auto-generated>
#region using
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
 
#endregion

namespace AutoStock.Data;


public class AccountMetaData
{
    
	public int AccountId {get; set;}

	public string AccountNumber {get; set;}

	public int AccountTypeCode {get; set;}

	public int CurrentAmount {get; set;}

	public int CurrentCurrency {get; set;}

	public bool Enabled {get; set;}

	public string Memo {get; set;}

	public int StockFirmCode {get; set;}
} 
