//<auto-generated> This file has been generated by Gccg. </auto-generated>
#region using
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
 
#endregion

namespace AutoStock.Data;


public class AccountDetailHistoryMetaData
{
    
	public int AccountDetailHistoryId {get; set;}

	public int AccountId {get; set;}

	public string Memo {get; set;}

	public int? Profits {get; set;}

	public int PurchasePrice {get; set;}

	public int PurchaseQuantity {get; set;}

	public DateTime PurchasedAt {get; set;}

	public int SellPrice {get; set;}

	public int SellQuantity {get; set;}

	public DateTime SoledAt {get; set;}

	public int StockId {get; set;}
} 
