//<auto-generated> This file has been generated by Gccg. </auto-generated>
#region using
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
 
#endregion

namespace AutoStock.Data;


public class CodeCategoryMetaData
{
    
	public int CodeCategoryId {get; set;}

	public string Text {get; set;}
} 
