//<auto-generated> This file has been generated by Gccg. </auto-generated>
#region using
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
 
#endregion

namespace AutoStock.Data;


public class StockMetaData
{
    
	public int StockId {get; set;}

	public bool Enabled {get; set;}

	public int LocationCode {get; set;}

	public string Memo {get; set;}

	public string Name {get; set;}

	public int NationalityCode {get; set;}

	public string StockCode {get; set;}
} 
