//<auto-generated> This file has been generated by Gccg. </auto-generated>
#region using
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
 
#endregion

namespace AutoStock.Data;


public class TokenMetaData
{
    
	public int TokenId {get; set;}

	public string AccessToken {get; set;}

	public bool Enabled {get; set;}

	public DateTime ExpiredAt {get; set;}

	public string Memo {get; set;}

	public int TypeCode {get; set;}
} 
